# Course - Introduction to R 

### title:- "Introduction to R Programming"
### author:- "Rashida Parveen"
### date:- "May 21, 2021"

##### NOTE: 
1. Your code MUST execute without any errors. 
2. You can add more lines in your code as required.

## Section 1: Data Types and Operations Pt. 1

### Question 1 
**Create the variables with the following composition:**
1. A vector containing each letter of your first name as its elements.
2. A variable that contains your name concatenated from the vector created in (1)
3. A variable containing a sequence from 100 to 120.
4. Create a matrix of 3x3 dimensions that contains the even sequence of numbers starting from 2.
5. Assign names to the variables.

In [ ]:
#### Start solution ####

In [1]:
x <- c('R','A','S','H','I','D','A')
x

[1] "R" "A" "S" "H" "I" "D" "A"

In [3]:
name <- 'RASHIDA'
name

[1] "RASHIDA"

In [4]:
numbers <- 100:120
numbers

[1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120

In [5]:
b <- matrix(seq(2,18, by = 2 ),nrow = 3,ncol = 3)
b

[,1] [,2] [,3]
[1,] 2     8   14  
[2,] 4    10   16  
[3,] 6    12   18

In [6]:
x <- 1:4

names(x) <- c('Col A','Col B','Col C','Col D')
x

Col A Col B Col C Col D 
    1     2     3     4

In [ ]:
#### End solution ####

### Question 2
**Create a factor variable emp_status:**
1. Containing the categorical variables: Employed, Unemployed, Self-Employed, with each level appearing atleast more than 2.
2. Display the levels and the factor variable as a table.
3. Unclass the elements of the factor variable.

In [4]:
#### Start solution ####

In [7]:
f <- factor(c('Employed','Unemployed','Self-Employed','Employed','Self-Employed','Unemployed','Employed','Self-Employed','Unemployed','Employed'))

In [8]:
f

[1] Employed      Unemployed    Self-Employed Employed      Self-Employed
 [6] Unemployed    Employed      Self-Employed Unemployed    Employed     
Levels: Employed Self-Employed Unemployed

In [9]:
table(f)

f
     Employed Self-Employed    Unemployed 
            4             3             3 

In [10]:
unclass(f)

[1] 1 3 2 1 2 3 1 2 3 1
attr(,"levels")
[1] "Employed"      "Self-Employed" "Unemployed"

In [3]:
#### End solution ####

### Question 3
**Create a dataframe object called bank_customers:**
1. the data frame will have three columns: CustomerID, hasAccount, totalBalance
2. Fill the data as follows
    a. Alicia does not have an account. She is here for inquiry 
    b. Nancy is here to check on her account balance of USD 10,000.
    c. Fernando is here to deposit USD 100 in his account which had no balance.
    d. Louis will withdraw all his money from the account that had USD 2,000. 
    e. Diane is here for information. 
3. For customers that do not have a value, use NA as placeholder.
4. Print the number of rows, columns and names for the data frame.

In [ ]:
#### Start solution ####

In [11]:
bank_customers <- data.frame(Customer_ID = c('Alicia','Nancy','Farnado','Louis','Diane'),Has_Account=c('NO','Yes','Yes','Yes','No') ,Total_Balance = c(NA,10000,NA,2000,NA) )
bank_customers

Customer_ID Has_Account Total_Balance
1 Alicia      NO             NA        
2 Nancy       Yes         10000        
3 Farnado     Yes            NA        
4 Louis       Yes          2000        
5 Diane       No             NA

In [12]:
nrow(bank_customers)

[1] 5

In [14]:
ncol(bank_customers)

[1] 3

In [15]:
names(bank_customers)

[1] "Customer_ID"   "Has_Account"   "Total_Balance"

In [2]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 2: Control Structures 

### Question 1
**Create a variable containing a sequence of numbers from 1 to 100:**
1. Iterate over the variables and print those numbers which are prime.

**Create a variable var with a value of 1:**
1. Create a while loop and increase the value of var at each iteration. 
2. When you reach the 10th prime number, terminate the loop and print the number.

In [5]:
#### Start solution ####

In [16]:
variable <- c(1:100)
for(i in variable){
    if (i == 1)next;
    is_prime <- TRUE
    x <- seq(2,i-1)
    for(z in x){
        if(i%%z==0){
            is_prime <- FALSE
            break
        }
    } 
    ##cat(sprintf("%s is a prime number: %s\n", i, is_prime))
    if (is_prime){
        print(i)
    }
}

[1] 3
[1] 5
[1] 7
[1] 11
[1] 13
[1] 17
[1] 19
[1] 23
[1] 29
[1] 31
[1] 37
[1] 41
[1] 43
[1] 47
[1] 53
[1] 59
[1] 61
[1] 67
[1] 71
[1] 73
[1] 79
[1] 83
[1] 89
[1] 97


In [17]:
numbers <- c(1:100)
var <-1;
prime_counter <- 1;
while(prime_counter <= 10){
  i <- numbers[var]
  var <- var + 1
  if (i == 1) next;
  is_prime <- TRUE;
  z <- seq(2,i - 1)
  for(b in z){
    if(i %% b==0){
      is_prime <- FALSE
      break
    }
  }
  if(is_prime){
      prime_counter <- prime_counter + 1
  }
}
print(numbers[var-1])

[1] 31


In [6]:
#### End solution ####

### Question 2
**Create a matrix of size 3x3 called mat_1:**
1. Iterate over all the values one by one and print the element as well as the position in the matrix (row, col)

In [9]:
#### Start solution ####

In [19]:
mat_1 <- matrix(c(1:9),nrow = 3 ,ncol = 3)
print(mat_1)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [20]:
print(mat_1[1,1])

[1] 1


In [22]:
print(mat_1[2,1])

[1] 2


In [23]:
print(mat_1[3,1])

[1] 3


In [24]:
print(mat_1[1,2])

[1] 4


In [26]:
print(mat_1[2,2])

[1] 5


In [27]:
print(mat_1[3,2])

[1] 6


In [28]:
print(mat_1[1,3])

[1] 7


In [29]:
print(mat_1[2,3])

[1] 8


In [30]:
print(mat_1[3,3])

[1] 9


In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 3: Functions

### Question 1
**Create a function called gcd that finds the greatest common divisor of two numbers a and b:**
1. a and b, should be taken as input.
2. The function must print the GCD as well as return it.
3. The output must be saved in a variable called answer.

In [9]:
#### Start solution ####

In [31]:
Factor <- function(divisibleNumber){
    flist <- list()
    counter <- 1;
    for (factor in seq(1, divisibleNumber)){
        if(divisibleNumber %% factor == 0){
            flist[counter] = factor
            counter <- counter + 1
        }
    }
    return(flist)
}
GCD <- function (a,b){
    aList <- Factor(a)
    bList <- Factor(b)
    commonList <- intersect(aList,bList)
    maxcommonfactor <-max(sapply(commonList, max))
    print(maxcommonfactor)
    return(maxcommonfactor)
}
a <- 8
b <- 18
answer <-GCD (a,b)
cat(sprintf("A = %s,B = %s and GCD is %s \n",a,b,answer))

[1] 2
A = 8,B = 18 and GCD is 2 


In [14]:
#### End solution ####

### Question 2
**Create a function called allConditionsMeet, that checks whether two expressions evaluate to true:**
1. a and b, should be taken as input.
2. the function should check if a and b, both conditions, evaluate to True.
3. The function must returns a boolean value.
4. Using a method, print the arguments that function takes.

In [9]:
#### Start solution ####

In [33]:
allConditionsMeet <- function(a,b) {
    print(a)
    print(b)
    cond_1 <- if(a) return (TRUE) else return(FALSE)
    cond_2 <- if(b) return (TRUE) else return(FALSE)
    return(cond_1 && cond_2)
}
a <- 3==3
b <- 9==9
print(allConditionsMeet(a,b))

[1] TRUE
[1] TRUE
[1] TRUE


In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 4: Vectorized Operations

### Question 1
**Create two matrices matrix_1 and matrix_2 of dimensions 2x3 and 3x2:**
1. Perform element-wise multiplication.
2. Perform matrix multipilcation. 

**Create a 2x2 matrix my_mat:**
1. Write a function to find the determinant of the matrix.

In [9]:
#### Start solution ####

In [71]:
mat_1 <- matrix(1:6, nrow = 2,ncol = 3)
mat_1
mat_2 <- matrix(7:12,nrow = 3,ncol = 2)
mat_2

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2]
[1,] 7    10  
[2,] 8    11  
[3,] 9    12

In [70]:
mat_1 <- matrix(1:6, nrow = 2,ncol = 3)
mat_2 <- matrix(7:12,nrow = 3,ncol = 2)
mat_1 * mat_1


[,1] [,2] [,3]
[1,] 1     9   25  
[2,] 4    16   36

In [41]:
mat_2 <- matrix(7:12,nrow = 2,ncol = 3)
mat_2 * mat_2

[,1] [,2] [,3]
[1,] 49    81  121 
[2,] 64   100  144

In [72]:
mat_1%*%mat_2

[,1] [,2]
[1,]  76  103 
[2,] 100  136

In [38]:
matrix <- matrix(1:4,nrow = 2,ncol = 2)
matrix
det(matrix)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[1] -2

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 5: Date and Time in R

### Question 1
**Use the current date and time and store them into variables curr_date and curr_time respectively: [use sys]**
1. Convert both into date and time objects using the appropriate functions.
2. Print the weekday, year, second and hour using the appropriate function and variables.

In [9]:
#### Start solution ####

In [43]:
curr_date <- Sys.time()
curr_date

[1] "2021-05-21 09:22:17 PKT"

In [44]:
p <- as.POSIXlt(curr_date)
p

[1] "2021-05-21 09:22:17 PKT"

In [45]:
unclass(p)

$sec
[1] 17.95665

$min
[1] 22

$hour
[1] 9

$mday
[1] 21

$mon
[1] 4

$year
[1] 121

$wday
[1] 5

$yday
[1] 140

$isdst
[1] 0

$zone
[1] "PKT"

$gmtoff
[1] 18000

attr(,"tzone")
[1] ""     "PKT"  "PKST"

In [14]:
#### End solution ####

### Question 2
**Create a variable to store current date/time**
1. Create another variable that stores and set the timezone as GMT-5
2. Find the difference between your current time and the GMT-5 timezone.

In [9]:
#### Start solution ####

In [57]:
curr_date<-Sys.time()
curr_date

[1] "2021-05-21 09:46:26 PKT"

In [58]:
p<-as.POSIXlt(curr_date)
p

[1] "2021-05-21 09:46:26 PKT"

In [59]:
names(unclass(p))

[1] "sec"    "min"    "hour"   "mday"   "mon"    "year"   "wday"   "yday"  
 [9] "isdst"  "zone"   "gmtoff"

In [60]:
p $ zone
x <- as.POSIXct ('2021-5-19 12:17:25')
y <- as.POSIXct ('2021-5-19 11 07:19:30',tz = 'GMT')
y-x

[1] "PKT"

Time difference of -7.290278 hours

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 6: Loop Functions

### Question 1
**Create a function to calculate mean and standard deviation of the provided data**
1. Create a sequence of numbers from 100 to 150 store in a variable called numbers.
1. Use lapply, sapply, apply and tapply to implement the functions on "numbers" [only on the second half of the sequence for tapply]

In [9]:
#### Start solution ####

In [47]:
numbers  <- list(100:150)
numbers

[[1]]
 [1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
[39] 138 139 140 141 142 143 144 145 146 147 148 149 150

In [48]:
lapply(numbers,mean)

[[1]]
[1] 125

In [49]:
lapply(numbers,sd)

[[1]]
[1] 14.86607

In [50]:
sapply(numbers,mean)

[1] 125

In [51]:
sapply(numbers,sd)

[1] 14.86607

In [52]:
numbers <- matrix(100:150)

apply(numbers,2,mean)

[1] 125

In [53]:
numbers <- matrix(100:150)
apply(numbers,2,sd)

[1] 14.86607

In [54]:
numbers <- 126:150
numbers

[1] 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
[20] 145 146 147 148 149 150

In [55]:
f <- gl (1,25)
tapply(numbers,f,mean)

1 
138

In [56]:
tapply(numbers,f,sd)

1 
7.359801

In [14]:
#### End solution ####

### Question 2
**Create a matrix of dimensions 4x4**
1. Find the row-wise and column-wise mean of the matrix.
2. Print the values.

In [9]:
#### Start solution ####

In [61]:
matrix_1 <-matrix(1:16,nrow = 4,ncol = 4)
print(matrix_1)

     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    6   10   14
[3,]    3    7   11   15
[4,]    4    8   12   16


In [62]:
row_mean <- apply(matrix_1,1,mean)
row_mean

[1]  7  8  9 10

In [63]:
col_mean <- apply(matrix_1,2,mean)
col_mean

[1]  2.5  6.5 10.5 14.5

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 7: Data Split

### Question 1
**Using the data frame Orange:**
1. Using split function to break down the dataset on circumference and store it in 'split_data' variable. 
2. Print the values for split_data where circumference is 30 and 75.
3. Find the average age of the tree when the circumference is 30 and when circumference is 214.


The dataset is loaded and the variable Orange contains the respective dataset.

In [21]:
library(datasets)

In [25]:
head(Orange)

Tree age  circumference
1 1     118  30          
2 1     484  58          
3 1     664  87          
4 1    1004 115          
5 1    1231 120          
6 1    1372 142

In [9]:
#### Start solution ####

In [64]:
split_data <- split(Orange,Orange$circumference)
print(split_data)

$`30`
   Tree age circumference
1     1 118            30
15    3 118            30
29    5 118            30

$`32`
   Tree age circumference
22    4 118            32

$`33`
  Tree age circumference
8    2 118            33

$`49`
   Tree age circumference
30    5 484            49

$`51`
   Tree age circumference
16    3 484            51

$`58`
  Tree age circumference
2    1 484            58

$`62`
   Tree age circumference
23    4 484            62

$`69`
  Tree age circumference
9    2 484            69

$`75`
   Tree age circumference
17    3 664            75

$`81`
   Tree age circumference
31    5 664            81

$`87`
  Tree age circumference
3    1 664            87

$`108`
   Tree  age circumference
18    3 1004           108

$`111`
   Tree age circumference
10    2 664           111

$`112`
   Tree age circumference
24    4 664           112

$`115`
   Tree  age circumference
4     1 1004           115
19    3 1231           115

$`120`
  Tree  age circumference
5  

In [65]:
split_data$'30'

Tree age circumference
1  1    118 30           
15 3    118 30           
29 5    118 30

In [66]:
split_data$'75'

Tree age circumference
17 3    664 75

In [67]:
sapply(list(split_data$'30'$age),mean)

[1] 118

In [68]:
sapply(list(split_data$'214'$age),mean)

[1] 1582

In [14]:
#### End solution ####


### Save it and push .ipynb and .html file to your Github Repository
## GOOD JOB! You have successfully finished the course!